### ISSUE TITLE
Telegram Bot Airdrop Automation

### ISSUE THREAD

**Issue by shfatislam** [daomaiauto/memefi-bot#1]
Hello Bro can you hack this telegram bot game

Hello Bro can you hack this telegram bot game

https://t.me/catizenbot/gameapp?startapp=r_3_3254911

This is a earning game can you hack

![Screenshot_20240424_233429_Telegram](https://github.com/daomaiauto/memefi-bot/assets/129420596/b2198d27-d795-4143-a7ea-aeb278e3fe48)
![Screenshot_20240424_233502_Telegram](https://github.com/daomaiauto/memefi-bot/assets/129420596/857f9dd7-d396-4365-8108-800067b554ec)
![Screenshot_20240424_233535_Telegram](https://github.com/daomaiauto/memefi-bot/assets/129420596/2cb127ce-7cbb-4521-95ea-0665083c26eb)

And if you can't hack the game then can you make auto bot for this game.  I am giving you the screenshots for you to check them out

And to buy autobots for this game you need 3900 fish tokens which is worth about 12 dollars.  And I joined here with 13 telegram accounts so it is not possible for me to buy this auto bot for each account with so many dollars.  So can you make an auto bot for it or hack the game itself?  Don't forget to let me know if you can.

**Comment by daomaiauto** [comment]
ok i do it later

**Comment by daomaiauto** [comment]
check this bro https://github.com/oppan31/catizen-auto-bot
